# Generated by Django 5.2.6 on 2026-01-28 00:00

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField(help_text='Mileage in km')),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('city', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleVehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sale_vehicles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.vehicleforsale')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
