# Generated by Django 5.2.6 on 2026-01-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevehicleimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Use this for Google Drive or external links', null=True),
        ),
    ]
